const games = [
  {
    name: "Split Fiction (Xbox Series X|S) XBOX LIVE Key EUROPE",
    platform: "Xbox Live",
    location: "EUROPE",
    price: 49.99,
    image_url_number: "split_fiction_1_q9pxzx",
    platform_image_number: "xbox_platform_img_aautgy",
    discount_price: 35.11,
    discount_percent: 30,
    cash_back: 3.86,
    favourites: 599,
    can_be_activated: true
  },
  {
    name: "Split Fiction EA App Key (PC) GLOBAL",
    platform: "EA App",
    location: "GLOBAL",
    price: 49.99,
    image_url_number: "split_fiction_1_q9pxzx",
    platform_image_number: "ea_platform_img_plpujw",
    discount_price: 38.88,
    discount_percent: 22,
    cash_back: 5.83,
    favourites: 775,
    can_be_activated: false
  }, 
  {
    name: "Split Fiction (Xbox Series X|S) XBOX LIVE Key GLOBAL",
    platform: "Xbox Live",
    location: "GLOBAL",
    price: 49.99,
    image_url_number: "split_fiction_1_q9pxzx",
    platform_image_number: "xbox_platform_img_aautgy",
    discount_price: 35.27,
    discount_percent: 29,
    cash_back: 3.88,
    favourites: 1114,
    can_be_activated: false
  },
  
  {
    name: "Split Fiction (Nintendo Switch 2) eShop Key EUROPE",
    platform: "Nintendo",
    location: "EUROPE",
    price: 36.40,
    image_url_number: "split_fiction_nintendo_jkko2x",
    platform_image_number: "nintendo_platform_img_gzoyyk",
    discount_price: null,
    discount_percent: null,
    cash_back: 4.00,
    favourites: 346,
    can_be_activated: true
  },
  {
    name: "Split Fiction Steam Key (PC) GLOBAL",
    platform: "Steam",
    location: "GLOBAL",
    price: 49.99,
    image_url_number: "split_fiction_1_q9pxzx",
    platform_image_number: "steam_platform_img_fwzkpg",
    discount_price: 47.99,
    discount_percent: 4,
    cash_back: 5.28,
    favourites: 1225,
    can_be_activated: false
  },
  {
    name: "Split Fiction (ENG) EA App Key (PC) GLOBAL",
    platform: "EA App",
    location: "GLOBAL",
    price: 41.30,
    image_url_number: "split_fiction_1_q9pxzx",
    platform_image_number: "ea_platform_img_plpujw",
    discount_price: null,
    discount_percent: null,
    cash_back: 4.54,
    favourites: 58,
    can_be_activated: true
  },
  {
    name: "Split Fiction EA App Key (PC) EUROPE",
    platform: "EA App",
    location: "EUROPE",
    price: 46.50,
    image_url_number: "split_fiction_1_q9pxzx",
    platform_image_number: "ea_platform_img_plpujw",
    discount_price: null,
    discount_percent: null,
    cash_back: 5.12,
    favourites: 27,
    can_be_activated: false
  },
  {
    name: "Split Fiction (Xbox Series X|S) XBOX LIVE Key UNITED STATES",
    platform: "Xbox Live",
    location: "UNITED STATES",
    price: 28.00,
    image_url_number: "split_fiction_1_q9pxzx",
    platform_image_number: "xbox_platform_img_aautgy",
    discount_price: null,
    discount_percent: null,
    cash_back: 3.08,
    favourites: 445,
    can_be_activated: true
  },
  {
    name: "Split Fiction (Nintendo Switch 2) eShop Key UNITED STATES",
    platform: "Nintendo",
    location: "UNITED STATES",
    price: 38.62,
    image_url_number: "split_fiction_1_q9pxzx",
    platform_image_number: "nintendo_platform_img_gzoyyk",
    discount_price: null,
    discount_percent: null,
    cash_back: 4.25,
    favourites: 18,
    can_be_activated: true
  },
  {
    name: "Split Fiction (Xbox Series X|S) XBOX LIVE Key CANADA",
    platform: "Xbox Live",
    location: "CANADA",
    price: 40.24,
    image_url_number: "split_fiction_1_q9pxzx",
    platform_image_number: "xbox_platform_img_aautgy",
    discount_price: null,
    discount_percent: null,
    cash_back: 4.43,
    favourites: 123,
    can_be_activated: true
  },
  {
    name: "EA SPORTS™ FIFA 23 Standard Edition Xbox Series X|S Key GLOBAL",
    platform: "Xbox Live",
    location: "GLOBAL",
    price: 79.99,
    image_url_number: "fifa_1_r3njvb",
    platform_image_number: "xbox_platform_img_aautgy",
    discount_price: 26.34,
    discount_percent: 67,
    cash_back: 2.90,
    favourites: 1824,
    can_be_activated: false
  },
  {
    name: "EA SPORTS™ FIFA 23 Standard Edition Xbox One Key GLOBAL",
    platform: "Xbox Live",
    location: "GLOBAL",
    price: 69.99,
    image_url_number: "fifa_2_n7yk5z",
    platform_image_number: "xbox_platform_img_aautgy",
    discount_price: 21.87,
    discount_percent: 69,
    cash_back: 2.41,
    favourites: 2812,
    can_be_activated: false
  },
  {
    name: "EA SPORTS™ FIFA 23 Standard Edition Xbox Series X|S Key EUROPE",
    platform: "Xbox Live",
    location: "EUROPE",
    price: 79.99,
    image_url_number: "fifa_1_r3njvb",
    platform_image_number: "xbox_platform_img_aautgy",
    discount_price: 25.63,
    discount_percent: 68,
    cash_back: 2.82,
    favourites: 1012,
    can_be_activated: true
  },
  {
    name: "EA SPORTS™ FIFA 23 Ultimate Edition Xbox One & Xbox Series X|S Key EUROPE",
    platform: "Xbox Live",
    location: "EUROPE",
    price: 99.99,
    image_url_number: "fifa_3_vvwooc",
    platform_image_number: "xbox_platform_img_aautgy",
    discount_price: 42.27,
    discount_percent: 58,
    cash_back: 4.65,
    favourites: 298,
    can_be_activated: false
  },
  {
    name: "EA SPORTS™ FIFA 23 Standard Edition Xbox One Key EUROPE",
    platform: "Xbox Live",
    location: "EUROPE",
    price: 69.99,
    image_url_number: "fifa_1_r3njvb",
    platform_image_number: "xbox_platform_img_aautgy",
    discount_price: 38.50,
    discount_percent: 58,
    cash_back: 4.24,
    favourites: 1163,
    can_be_activated: true
  },
  {
    name: "FIFA 23 : 5900 FIFA Points (Xbox One/Xbox Series X|S) Xbox Live Key GLOBAL",
    platform: "Xbox Live",
    location: "GLOBAL",
    price: 2158.90,
    image_url_number: "fifa_5900_ybpbxi",
    platform_image_number: "xbox_platform_img_aautgy",
    discount_price: null,
    discount_percent: null,
    cash_back: null,
    favourites: 326,
    can_be_activated: true
  },
  {
    name: "FIFA 23 (EN/PL/CZ/TR) (PC) Origin Key GLOBAL",
    platform: "Origin",
    location: "GLOBAL",
    price: 69.99,
    image_url_number: "fifa_1_r3njvb",
    platform_image_number: "origin_platform_img_w9t9ev",
    discount_price: 21.81,
    discount_percent: 69,
    cash_back: 2.40,
    favourites: 1550,
    can_be_activated: true
  },
  {
    name: "FIFA 23 (ENG/PL) (PC) Origin Key EUROPE",
    platform: "Origin",
    location: "EUROPE",
    price: 27.18,
    image_url_number: "fifa_1_r3njvb",
    platform_image_number: "origin_platform_img_w9t9ev",
    discount_price: null,
    discount_percent: null,
    cash_back: 2.99,
    favourites: 17,
    can_be_activated: false
  },
  {
    name: "FIFA 23 (PC) Origin Key GLOBAL",
    platform: "Origin",
    location: "GLOBAL",
    price: 69.99,
    image_url_number: "fifa_1_r3njvb",
    platform_image_number: "origin_platform_img_w9t9ev",
    discount_price: 27.71,
    discount_percent: 60,
    cash_back: 3.05,
    favourites: 23941,
    can_be_activated: true
  },
  {
    name: "FIFA 23 : 2800 FIFA Points (PC) Origin Key GLOBAL",
    platform: "Origin",
    location: "GLOBAL",
    price: 24.99,
    image_url_number: "fifa_1_r3njvb",
    platform_image_number: "origin_platform_img_w9t9ev",
    discount_price: 7.22,
    discount_percent: 60,
    cash_back: 6.00,
    favourites: 737,
    can_be_activated: true
  },
  {
    name: "EA SPORTS™ FIFA 23 Ultimate Team Voucher (DLC) (PS5) PSN Key EUROPE",
    platform: "PSN",
    location: "EUROPE",
    price: 0.39,
    image_url_number: "fifa_2_n7yk5z",
    platform_image_number: "psn_platform_img_fte0ai",
    discount_price: null,
    discount_percent: null,
    cash_back: 0.03,
    favourites: 737,
    can_be_activated: false
  },
  {
    name: "Red Dead Redemption 2 PC Rockstar Key GLOBAL",
    platform: "Rockstar Games Launcher",
    location: "GLOBAL",
    price: 59.99,
    image_url_number: "red_redumption_1_twbmd3",
    platform_image_number: "rockstar_platform_img_jruqdc",
    discount_price: 12.41,
    discount_percent: 79,
    cash_back: 1.37,
    favourites: 25911,
    can_be_activated: true
  },
  {
    name: "Red Dead Redemption 2: Ultimate Edition Rockstar Games Launcher Key GLOBAL",
    platform: "Rockstar Games Launcher",
    location: "GLOBAL",
    price: 99.99,
    image_url_number: "red_redumption_1_twbmd3",
    platform_image_number: "rockstar_platform_img_jruqdc",
    discount_price: 15.69,
    discount_percent: 84,
    cash_back: 1.73,
    favourites: 6972,
    can_be_activated: true
  },
  {
    name: "Red Dead Redemption 2 (PC) Green Gift Key GLOBAL",
    platform: "Green gift",
    location: "GLOBAL",
    price: 59.99,
    image_url_number: "red_redumption_1_twbmd3",
    platform_image_number: "Green_gift_platform_img_kzsr4k",
    discount_price: 11.08,
    discount_percent: 82,
    cash_back: 1.22,
    favourites: 9309,
    can_be_activated: false
  },
  {
    name: "Red Dead Redemption 2: Ultimate Edition (PC) Rockstar Games Launcher Key EUROPE",
    platform: "Rockstar Games Launcher",
    location: "EUROPE",
    price: 99.99,
    image_url_number: "red_redumption_1_twbmd3",
    platform_image_number: "rockstar_platform_img_jruqdc",
    discount_price: 15.71,
    discount_percent: 84,
    cash_back: 1.73,
    favourites: 1135,
    can_be_activated: true
  },
  {
    name: "Red Dead Redemption 2 (PC) Rockstar Games Launcher Key EUROPE",
    platform: "Rockstar Games Launcher",
    location: "EUROPE",
    price: 59.99,
    image_url_number: "red_redumption_1_twbmd3",
    platform_image_number: "rockstar_platform_img_jruqdc",
    discount_price: 12.19,
    discount_percent: 80,
    cash_back: 1.34,
    favourites: 2303,
    can_be_activated: true
  },
  {
    name: "Red Dead Redemption 2 (PC) Green Gift Key EUROPE",
    platform: "Green gift",
    location: "EUROPE",
    price: 11.17,
    image_url_number: "red_redumption_1_twbmd3",
    platform_image_number: "Green_gift_platform_img_kzsr4k",
    discount_price: null,
    discount_percent: null,
    cash_back: 1.23,
    favourites: 1185,
    can_be_activated: true
  },
  {
    name: "Red Dead Redemption 2: Ultimate Edition Rockstar Games Launcher Key UNITED STATES/EMEA",
    platform: "Rockstar Games Launcher",
    location: "UNITED STATES, EMEA",
    price: 15.94,
    image_url_number: "red_redumption_1_twbmd3",
    platform_image_number: "rockstar_platform_img_jruqdc",
    discount_price: null,
    discount_percent: null,
    cash_back: 1.75,
    favourites: 395,
    can_be_activated: false
  },
  {
    name: "Red Dead Redemption 2: Ultimate Edition Rockstar Games Launcher Key UNITED STATES/EUROPE",
    platform: "Rockstar Games Launcher",
    location: "UNITED STATES, EUROPE",
    price: 15.78,
    image_url_number: "red_redumption_1_twbmd3",
    platform_image_number: "rockstar_platform_img_jruqdc",
    discount_price: null,
    discount_percent: null,
    cash_back: 1.74,
    favourites: 436,
    can_be_activated: true
  },
  {
    name: "Red Dead Redemption 2 (Xbox One) Xbox Live Key EUROPE",
    platform: "Xbox Live",
    location: "EUROPE",
    price: 14.85,
    image_url_number: "red_redumption_2_rkcn36",
    platform_image_number: "xbox_platform_img_aautgy",
    discount_price: null,
    discount_percent: null,
    cash_back: 1.63,
    favourites: 2384,
    can_be_activated: false
  }
];

module.exports = games;